#include "TinyRPC/ServiceMacro.hpp"
#include <string>

QUICK_RPC_0_SERVICE_NAME(IntToString)
QUICK_RPC_1_REQUEST_BEFORE_FIELDS
  int64_t i;
QUICK_RPC_2_REQUEST_FIELDS_SERIALIZED(i)
QUICK_RPC_3_RESPONSE_BEFORE_FIELDS
  std::string i;
QUICK_RPC_4_RESPONSE_FIELDS_SERIALIZED(i)
